### ISSUE TITLE
Setup Docker

### ISSUE THREAD

**Issue by Jonas-Karl** [DHBW-Mailflow/mailserver#2]
**Description**
As a hosting service I want to be able to host the mailserver independently from the operating system so that I dont have to care about the setup

**Ready Criteria**
- [ ] everyone understood the scope of this ticket
- [ ] atleast one person is assigned
- [ ] Reasons for Docker are known

**Acceptance Criteria**
- [ ] Mailserver runs in Docker

**Scope**
- [x] Docker

**Comment by jens1o** [comment]
fixed by #63
