### ISSUE TITLE
Use consistent code-style

### ISSUE THREAD

**Issue by jens1o** [DHBW-Mailflow/mailserver#60]
**Description**
As a developer I want to consistent code style so that I can navigate in the code faster and don't risk to have lines attributed to others due to automatic, different, formatting.

**Ready Criteria**
- [ ] everyone understood the scope of this ticket
- [ ] atleast one person is assigned

**Acceptance Criteria**
- [ ] Agree on one code-style
- [ ] Have code-style setup automatically in every IDE (IntelliJ, VSCode)
- [ ] Have code-style check as part of integration pipeline
- [ ] The assigned person has guided the others to set up the format correctly for the "Extension Pack for Java"
- [ ] Automatic formatting is applied if possible 

**Scope**
❌ CI

**Comment by seiferla** [comment]
[Google Codestyle IntelliJ](https://gerrit.cloudera.org/Documentation/dev-intellij.html#_code_style)
[VSCode Google Codestyle](https://code.visualstudio.com/docs/java/java-linting)
