### ISSUE TITLE
[Quality] reformat entire code base

### ISSUE THREAD

**Issue by Jonas-Karl** [DHBW-Mailflow/mailserver#92]
**Description**
As a developer I want to have a consistent code style in my code base

**Ready Criteria**
- [ ] everyone understood the scope of this ticket
- [ ] atleast one person is assigned

**Acceptance Criteria**
- [ ] everyone has automatic import optimization turned on
- [ ] everyone has automatic code formatting turned on
- [ ] the codebase is formatted

**Scope**
✅ the entire codebase

**Additional context**

**Comment by jens1o** [comment]
could be done together with the `@author`-Attribution for each class

**Comment by jens1o** [comment]
fixed with #96
